# Generated by Django 5.1.1 on 2024-10-21 04:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option1', models.CharField(max_length=100)),
                ('option2', models.CharField(max_length=100)),
                ('option3', models.CharField(max_length=100)),
                ('option4', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=255)),
                ('course_description', models.TextField(blank=True, null=True)),
                ('course_duration', models.DurationField()),
                ('age_category', models.CharField(choices=[('3-6', '3-6'), ('6-8', '6-8'), ('8+', '8+')], default='3-6', max_length=50)),
                ('product_model', models.CharField(choices=[('U10 pro', 'U10 pro'), ('U20 pro', 'U20 pro'), ('A1', 'A1'), ('A3', 'A3'), ('S30', 'S30'), ('S40', 'S40'), ('D3 pro', 'D3 pro'), ('AI MODULE 1S', 'AI MODULE 1S'), ('AI MODULE 5S', 'AI MODULE 5S'), ('AI MODULE 3S', 'AI MODULE 3S'), ('E7 pro', 'E7 pro')], default='U10 pro', max_length=100)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='OfflinePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_contact_name', models.CharField(max_length=100)),
                ('vendor_contact_number', models.CharField(max_length=15)),
                ('vendor_email', models.EmailField(max_length=100)),
                ('vendor_address', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact_name', models.CharField(max_length=100)),
                ('customer_contact_number', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_address', models.TextField()),
                ('payment_term', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('cheque', 'cheque'), ('neft', 'neft')], default='offline', max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('transaction_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(choices=[('U10 pro', 'U10 pro'), ('U20 pro', 'U20 pro'), ('A1', 'A1'), ('A3', 'A3'), ('S30', 'S30'), ('S40', 'S40'), ('D3 pro', 'D3 pro'), ('AI MODULE 1S', 'AI MODULE 1S'), ('AI MODULE 5S', 'AI MODULE 5S'), ('AI MODULE 3S', 'AI MODULE 3S'), ('E7 pro', 'E7 pro')], default='U10 pro', max_length=100)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('purchasedUser', 'purchasedUser'), ('CourseSubscribedUser', 'CourseSubscribedUser'), ('admin', 'admin'), ('visitor', 'visitor')], default='visitor', max_length=50)),
                ('subscription', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('basequestion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lmsappv1.basequestion')),
            ],
            bases=('lmsappv1.basequestion',),
        ),
        migrations.CreateModel(
            name='CertificationQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('option1', models.CharField(max_length=255)),
                ('option2', models.CharField(max_length=255)),
                ('option3', models.CharField(max_length=255)),
                ('option4', models.CharField(max_length=255)),
                ('answer', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lmsappv1.certification')),
            ],
        ),
        migrations.AddField(
            model_name='certification',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='lmsappv1.course'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_duration', models.DurationField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.course')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(max_length=100)),
                ('module_description', models.TextField()),
                ('module_type', models.CharField(choices=[('Introduction', 'Introduction'), ('Building', 'Building'), ('Activity', 'Activity')], default='Introduction', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='pptx_files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.task')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('receipt', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lmsappv1.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.course')),
                ('last_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsappv1.module')),
                ('last_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lmsappv1.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='lmsappv1.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserAssessmentScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to='lmsappv1.user')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.module'),
        ),
    ]
