# Generated by Django 5.1.2 on 2024-11-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0002_usercourseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourseprogress',
            name='course_images',
            field=models.CharField(blank=True, null=True),
        ),
    ]
