# Generated by Django 5.1.1 on 2024-10-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0002_course_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='activityid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='contentid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='introid',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='activity',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='intro',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
