# Generated by Django 5.1.2 on 2024-11-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0003_alter_usercourseprogress_course_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
