# Generated by Django 5.1.2 on 2024-12-31 08:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0003_subscriptionmoney_remove_transaction_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_cart', to='lmsappv1.product')),
                ('transact', models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='product_transaction', to='lmsappv1.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='lmsappv1.user')),
            ],
        ),
    ]
