# Generated by Django 5.1.1 on 2024-10-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0004_remove_module_activityid_remove_module_contentid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='activity',
            field=models.URLField(blank=True, null=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=models.URLField(blank=True, null=True, verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='module',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='overview',
            field=models.URLField(blank=True, null=True, verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='module',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
