# Generated by Django 5.1.2 on 2024-11-22 07:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0004_course_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCertificationScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_marks', models.IntegerField(default=0)),
                ('obtained_marks', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('certify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lmsappv1.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_score', to='lmsappv1.user')),
            ],
        ),
    ]
