# Generated by Django 5.1.1 on 2024-10-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0007_course_isconfirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
