# Generated by Django 5.1.1 on 2024-10-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0008_module_module_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productkit',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='productkit',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='productkit',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RemoveField(
            model_name='productkit',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='productkit',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productkit',
            name='age_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
