# Generated by Django 5.1.2 on 2025-01-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0008_alter_transaction_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
