# Generated by Django 5.1.1 on 2024-10-17 03:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0010_productkit_product_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflinePurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('vendor_contact_name', models.CharField(max_length=100)),
                ('vendor_contact_number', models.CharField(max_length=15)),
                ('vendor_email', models.EmailField(max_length=100)),
                ('vendor_address', models.TextField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_contact_name', models.CharField(max_length=100)),
                ('customer_contact_number', models.CharField(max_length=15)),
                ('customer_email', models.EmailField(max_length=100)),
                ('customer_address', models.TextField()),
                ('payment_term', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('cheque', 'cheque'), ('neft', 'neft')], default='offline', max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('transaction_number', models.CharField(max_length=100)),
                ('product_name', models.CharField(choices=[('U10 pro', 'U10 pro'), ('U20 pro', 'U20 pro'), ('A1', 'A1'), ('A3', 'A3'), ('S30', 'S30'), ('S40', 'S40'), ('D3 pro', 'D3 pro'), ('AI MODULE 1S', 'AI MODULE 1S'), ('AI MODULE 5S', 'AI MODULE 5S'), ('AI MODULE 3S', 'AI MODULE 3S'), ('E7 pro', 'E7 pro')], default='U10 pro', max_length=100)),
                ('product_price', models.FloatField()),
                ('product_quantity', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='OfflinePayment',
        ),
    ]
