# Generated by Django 5.1.2 on 2025-01-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0010_alter_course_course_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
