# Generated by Django 5.1.2 on 2024-12-23 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0010_product_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='isconfirmed',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='age_category',
        ),
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='product_model',
        ),
        migrations.AddField(
            model_name='course',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lmsappv1.product'),
        ),
    ]
