# Generated by Django 5.1.2 on 2024-12-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0011_rename_isconfirmed_course_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='duration',
        ),
        migrations.AlterField(
            model_name='certification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
