# Generated by Django 5.1.1 on 2024-10-08 07:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0003_module_activityid_module_contentid_module_introid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='activityid',
        ),
        migrations.RemoveField(
            model_name='module',
            name='contentid',
        ),
        migrations.RemoveField(
            model_name='module',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='module',
            name='introid',
        ),
        migrations.AddField(
            model_name='module',
            name='overview',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='overview'),
        ),
        migrations.AlterField(
            model_name='module',
            name='activity',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='module',
            name='content',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='content'),
        ),
    ]
