# Generated by Django 5.1.1 on 2024-10-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0009_rename_description_productkit_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productkit',
            name='product_cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
