# Generated by Django 5.1.1 on 2024-10-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
