# Generated by Django 5.1.1 on 2024-10-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0011_offlinepurchase_delete_offlinepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='product_model',
            field=models.CharField(choices=[('U10 pro', 'U10 pro'), ('U20 pro', 'U20 pro'), ('A1', 'A1'), ('A3', 'A3'), ('S30', 'S30'), ('S40', 'S40'), ('D3 pro', 'D3 pro'), ('AI MODULE 1S', 'AI MODULE 1S'), ('AI MODULE 5S', 'AI MODULE 5S'), ('AI MODULE 3S', 'AI MODULE 3S'), ('E7 pro', 'E7 pro')], default='U10 pro', max_length=100),
        ),
    ]
