# Generated by Django 5.1.1 on 2024-10-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsappv1', '0015_otp_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.TextField(max_length=4),
        ),
    ]
